name: Health Check

on:
  
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:

  health_check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run health check script
        run: |
          if curl -I "https://msdkeansburg.com" 2>&1 | grep -w "2011" ; then
            echo "msdkeansburg.com is up"
            exit 0
          else
            echo "msdkeansburg.com is down"
            exit 1
          fi

#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
