name: Health Check

on:
  
  # Schedules health check job every night at 8pm or 9pm EST / 1pm UTC 
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:

  health_check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run health check script
        run: |
          if curl -I "https://msdkeansburg.com" 2>&1 | grep -w "2011" ; then
            echo "msdkeansburg.com is up"
            exit 0
          else
            echo "msdkeansburg.com is down"
            exit 1
          fi

      # - name: Send mail
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v2
      #   with:
      #     # mail server settings
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     # user credentials
      #     # username: ${{ secrets.EMAIL_USERNAME }}
      #     # password: ${{ secrets.EMAIL_PASSWORD }}
      #     # email subject
      #     subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      #     # email body as text
      #     body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
      #     # comma-separated string, send email to
      #     to: bhavinpanchani9@gmail.com
      #     # from email name
      #     from: automation@msdkeansburg.com
