name: Health Check

on:
  
  # Schedules health check job every night at 8pm or 9pm EST / 1pm UTC 
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:

  health-check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run health check script
        run: |
          if curl -I "https://msdkeansburg.com" 2>&1 | grep -w "200" ; then
            echo "msdkeansburg.com is up"
            exit 0
          else
            echo "msdkeansburg.com is down"
            exit 1
          fi

      - name: Send mail
#         if: failure()
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MSD_EMAIL }}
          password: ${{ secrets.MSD_EMAIL_PASSWORD }}
          # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # subject: msdkeansburg.com is DOWN
          # body: "https://msdkeansburg.com is DOWN. \nFew things to checks \n1) Verify if there are any outage on Github or Github Pages. \n2) Please check if SSL is valid or expired. As SSL (https) needs to be valid for this test."
          subject: "${{ job.status.toUpperCase() }} : Health check for msdkeansburg.com"
          body: "Health check for https://msdkeansburg.com is ${{ job.status }}. \nBELOW ARE INSTRUCTIONS IF TEST FAILED: \n1) Verify if there are any outage on Github or Github Pages. \n2) Please check if SSL is valid or expired. As SSL (https) needs to be valid for this test."
          # comma-separated string, send email to
          to: ${{ secrets.BHAVIN_EMAIL}}
          from: MSD Automation
