name: Health Check

on:
  
  # Schedules health check job every night at 8pm or 9pm EST / 1pm UTC 
  schedule:
    # - cron: '0 1 * * *'
    # Testing for every hour
    - cron: '0 * * * *'  

  workflow_dispatch:

jobs:

  health-check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run health check script
        run: |
          if curl -I "https://msdkeansburg.com" 2>&1 | grep -w "200" ; then
            echo "msdkeansburg.com is up"
            exit 0
          else
            echo "msdkeansburg.com is down"
            exit 1
          fi
          
      - name: Send mail
#         if: failure()
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MSD_EMAIL }}
          password: ${{ secrets.MSD_EMAIL_PASSWORD }}
          subject: "${{ job.status }}"
          html_body:
            <html>
              <body>
                <h3>Health Check ${{ job.status }}</h3>
                <br>
                <p>https://msdkeansburg.com is not reachable</p>
                <br>
                <p>Below are some troubleshooting tips</p>
                <ul>
                  <li>Verify if there are any outage on Github or Github Pages.</li>
                  <li>Please check if SSL is valid or expired. As SSL (https) needs to be valid for this test.</li>
                </ul>
              </body>
            </html>
          to: ${{ secrets.BHAVIN_EMAIL}}
          from: MSD Keansburg Automation
